[project]
name = "wordle"
version = "0.0.1"
authors = [{ name = "Murilo Gustineli", email = "murilogustineli@gmail.com" }]
description = "Wordle helper package"
readme = "README.md"
requires-python = ">=3.10"
dependencies = ["numpy", "pandas", "tabulate"]

[project.scripts]
wordle = "wordle.cli:main"

[project.urls]
Homepage = "https://github.com/mgustineli/wordle"
Issues = "https://github.com/mgustineli/wordle/issues"

[dependency-groups]
dev = [
    "ipykernel",
    "jupyterlab",
    "matplotlib",
    "pre-commit",
    "pytest",
    "ruff",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["wordle", "wordle.data"]
namespaces = false

[tool.setuptools.package-data]
"wordle.data" = ["*.txt"]

[tool.pytest.ini_options]
testpaths = ["tests"]
